language: perl

os:
  - linux

perl:
  - "5.6"
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.28"
  - "5.30"
  - "5.32"
  - "blead"

before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
  - perl -V
  # Force latest versions of prereq modules
  # The cpan-install line is enough for perl >= 5.8
  - cpan-install --update-prereqs --deps

# 5.6 is a special case - no cpanm available,
# so force installation of dependencies with cpan
install: >
  if  [ "$TRAVIS_PERL_VERSION" = "5.6" ]; then
    echo Special Case for 5.6
    cpan Scalar::Util;
    cpan Perl::OSType;
    cpan IO::Uncompress::Unzip;
    cpan IO::Compress::Zip  ;
    cpan IO::Compress::Lzma;
  else
    echo TRAVIS_PERL_VERSION is $TRAVIS_PERL_VERSION
  fi
