language: perl

os:
  - linux
  
perl:
  - "5.6"
  - "5.8"
  - "5.10"        
  - "5.12"         
  - "5.14"         
  - "5.16"         
  - "5.18"         
  - "5.20"         
  - "5.22"         
  - "5.24"         
  - "5.26"         
  - "5.28"         
  - "5.30"         
  - "blead"  
  
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto

install:
  - perl -V
  - cpan-install --deps
  # Force latest version of these modules
  - cpan Scalar::Util
  - cpan Perl::OSType
  - cpan IO::Uncompress::Unzip
  - cpan IO::Compress::Zip  
  - cpan IO::Compress::Lzma
